### ISSUE TITLE
Hi Angelos

### ISSUE THREAD

**Issue by arxdsilva** [AValsamis/ports-service#1]
Thank you for taking the time to complete our test.
This is entirely part of the interview process.

There are no time constraints from my side, so you can provide fixes and/or discussion on your own time, at your own pace.

## Context
As you have referenced in the `readme.md` file, your app memory does not scale well as the storage grows.

## Requested Fix
Please provide:
1. a database implementation - substituting your current repository, it can be anyone that fits this task;
2. any code or files necessary to run the database alongside your application;
3. docs on how to run both;
4. document why you used that database.

We do appreciate your efforts to improve your test.

**Comment by AValsamis** [comment]
Hi Arthur, 
Thank you for taking the time to check my solution!
Apologies, I misunderstood the part in the assignment that mentioned an in-memory database. I thought that the requirement is an in-memory **storage** to reduce the implementation complexity (to simplify the assignment). I've addressed your comments in [this pull request](https://github.com/AValsamis/ports-service/pull/2).
